name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    - name: Install dependencies
      run: make build
    
    - name: Run unit tests
      run: make test
    
    - name: Run main program
      run: make run
      
    - name: Run clean
      run: make clean
